### ISSUE TITLE
room listeners not being fired

### ISSUE THREAD

**Issue by cesarpachon** [gamestdio/colyseus.js#10]
hi, first attempts with colyseus and colyseus.js.. using the simple chat_room example, the server is printing the join and leave events, but in client side I got the following warning in the console: 
colyseus.js: trying to send data while in 0 state
and the join callback is never fired. 
client side code: 
 ```
   var cclient = new Colyseus.Client("ws://localhost:3553");
    var room = cclient.join("main_region");
    room.onJoin.add(() => console.log("joined successfully!"));
```
output from the server:
```
[nodemon] starting `node server.js`
Listening on http://localhost:3553
Sy0END-PW joined ChatRoom!
Sy0END-PW left ChatRoom
ryW84wbDZ joined ChatRoom!
ryW84wbDZ left ChatRoom
```
server side code is just the same as in the chat_room example. 
perhaps I am missing something?

**Comment by endel** [comment]
Hey @cesarpachon,

Which version of `colyseus` and `colyseus.js` are you using?

I recommend using the latest alpha versions:
- colyseus.js@0.7.0-alpha.5
- colyseus@0.5.0-alpha.9

They're "alpha" just because the Unity3D client is not ready yet.

Let me know if you find any problem.

**Comment by cesarpachon** [comment]
hello, thanks for your reply! 
now I got a repetitive error in the console saying the port is in use, doesn't matter what number I choose (original value: port = process.env.PORT || 3553). I am working in Ubuntu. 
about the versioning: 
I installed colyseus through "npm  install colyseus" and  package.json said it was ^0.4.18. If I put "^colyseus@0.5.0-alpha.9" it installs the alpha.12 version. without the  "^" I got the alpha.9.. 
for the client, I just dowloaded the colyseus.js raw file right from github, as through npm I was not able to find the transpiled version in node_modules folder.  so checking the package json it says "0.7.0-alpha.5" in master branch so that one was ok.

**Comment by ScottyFillups** [comment]
Hi @cesarpachon,

The issue is that you're listening to `httpServer` on server-side. Migrating from 0.4 to 0.5, you now need to listen to `gameServer` instead. Read the following for more info:

https://github.com/gamestdio/colyseus/blob/master/MIGRATING.md#migrating-from-04-to-05

**Comment by endel** [comment]
@ScottyFillups thanks for your response.

@cesarpachon I suggest upgrading to the latest versions of the server (`0.5.6`) and client (`0.7.3`). Feel free to reopen this issue if you have any questions!
