### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by Jonovono** [gamestdio/colyseus.js#11]
Could this be used in react native?

I get the following error:

```
"Unable to resolve module `events` from `...../node_modules/backoff/lib/backoff.js`: Module does not exist in the module map
```

**Comment by endel** [comment]
This lib is a dependency from the [websocket.js](https://github.com/gamestdio/websocket.js).

Sorry for the late reply, I'm moving countries and I'll have a look into this soon.

**Comment by endel** [comment]
I've been investigating this and here are some notes for me to look at later.

After removing the `"events"` node module as a dependency, a couple of issues has been unlocked:

- `localStorage` - use AsyncStorage should be used instead
- `performance.now` - use `new Date()` instead.

**Comment by endel** [comment]
@Jonovono this client now supports react-native! 🎉 

Release: https://github.com/gamestdio/colyseus.js/releases/tag/0.7.2
More info: https://github.com/gamestdio/colyseus.js#react-native-compatibility

**Comment by endel** [comment]
Version `0.7.2` went wrong for the browser (typescript+webpack). `0.7.3` fixed it.

**Comment by Goblin-Knight** [comment]
My Code in React Native is below, but i got "Can't find variable:Symbol

"
import 'react-native-browser-polyfill';
import React, { Component } from 'react';
import * as Colyseus from "colyseus.js";
import {  
  Text,
  View,
  AsyncStorage
} from 'react-native';
window.localStorage = AsyncStorage;

export default class App extends Component<{}> {
  render() {
    return (
      <View>
        <Text>
          Welcome to React Native!
        </Text>        
      </View>
    );
  }
}
