### ISSUE TITLE
How can I use this framework in Egret?  Can't find singles.js

### ISSUE THREAD

**Issue by helloliuchen** [gamestdio/colyseus.js#18]
Hi~ 
      Thanks for developed this great framework.
      I am using Egret html engine which is using Typescript, I tried to import colyseus.js into Egret as third library by importing the dist folders ( Colysues.js, Client.d.ts, Connection.d.ts, index.d.ts, Protocol.d.ts, Room.d.ts),  but I met the problems, typescript can't find ''signals.js' in Client.d.ts.
      I am new to typescript, does that problem means that I have to import all the dependence js files' definitions?
     Thank you ~

**Comment by endel** [comment]
Hi @helloliuchen, can you share your project so I can reproduce your issue? Thanks

**Comment by helloliuchen** [comment]
sorry for reply late.

Here is my repo
https://github.com/helloliuchen/colyseus_test_with_egret

just add colyseus as third part library

**Comment by endel** [comment]
Hey @helloliuchen, thanks for sharing your project.

Currently there's no type definitions for the static `dist/colyseus.js` file. The type definitions are only for `commonjs` module system, which doesn't play nice with Egret's module system (global).

I'm afraid you'll have to use it without code-completion with Egret. You can remove the `.d.ts` you have for Colyseus and create `colyseus.d.ts` declaring it as type of `any`:

```typescript
/// colyseus.d.ts
declare var Colyseus: any;
```

(Issue https://github.com/gamestdio/colyseus.js/issues/9 relates to the same thing)

Cheers!

**Comment by helloliuchen** [comment]
It works!
Thank you very much!

**Comment by endel** [comment]
Global type definitions are finally available on [`colyseus.d.ts`](https://github.com/gamestdio/colyseus.js/blob/master/dist/colyseus.d.ts).

Thanks a lot @AlexanderKolarov for his pull-request (https://github.com/gamestdio/colyseus.js/pull/27)
