### ISSUE TITLE
How to import colyseus in React Native?

### ISSUE THREAD

**Issue by Goblin-Knight** [gamestdio/colyseus.js#19]
My Code in React Native is below, but i got "Can't find variable:Symbol"

import 'react-native-browser-polyfill';
import React, { Component } from 'react';
import * as Colyseus from "colyseus.js";
import {
Text, View, AsyncStorage
} from 'react-native';
window.localStorage = AsyncStorage;

export default class App extends Component<{}> {
render() {
return (
...
);
}
}

**Comment by endel** [comment]
Hi @Goblin-Knight,

Are you using Android for testing? This comment explains the problem: https://github.com/facebook/react-native/issues/15805#issuecomment-353199366

You can fix this by requiring `es6-symbol` polyfill:

```
npm install es6-symbol
```

Import the polyfill in your `main.js`:

```
require('es6-symbol/implement');
```

Cheers

**Comment by Goblin-Knight** [comment]
Many Thank!!! yes, i am using Android for testing, thank @endel  to told me the problem that cause by enable debugger feature, let start develop~ :)

**Comment by endel** [comment]
You're welcome!
