### ISSUE TITLE
Cannot send messages from iOS 7.0 and below

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus.js#2]
It seems no msgpack implementation works on iOS 7.0 and below. (Mobile Safari)

I already tried using [msgpack-lite](https://github.com/kawanet/msgpack-lite), [notepack](https://github.com/coinative/notepack) and [msgpack5](https://github.com/mcollina/msgpack5), and none of them were successful.

**Comment by rscata** [comment]
On iOS 9.3.5

`colyseus:matchmaking JOIN_ERROR: trying to join non-existing room (roomId: HkeUVR2JYG, clientOptions: undefined) +1h
`
It is the same problem ? 
thanks

**Comment by endel** [comment]
Hi, @rscata shouldn't be the same problem. Aren't you trying to join a non-existing room id? Cheers!

**Comment by rscata** [comment]
It seems like my error 
`colyseus:matchmaking JOIN_ERROR: trying to join non-existing room (roomId: HkeUVR2JYG, clientOptions: undefined)`
has been resolved if I updated the colyseus server from 0.8.13 to 0.8.14.

I was also tried in the older version 0.8.1 and there it worked.

Why did not it work?

However well it works on the latest version 0.8.14

Thanks.

**Comment by endel** [comment]
Good to know, @rscata! Some recent changes early `0.8.x` versions broke joining rooms by id, it was fixed since [0.8.12](https://github.com/gamestdio/colyseus/releases/tag/0.8.12). Let me know if you still find any problems there.

I'm closing this issue since iOS 7.0 and below aren't going to be supported. Cheers!

**Comment by rscata** [comment]
ok, thanks.
