### ISSUE TITLE
Can't find variable: Buffer in colyseus.js@0.8.2

### ISSUE THREAD

**Issue by Goblin-Knight** [gamestdio/colyseus.js#20]
![image](https://user-images.githubusercontent.com/616905/35815445-74026336-0ad3-11e8-98a8-c52648aecf65.png)

**Comment by Goblin-Knight** [comment]
I solve myself problem to add shim.js and import in my project
https://github.com/mvayngrib/rn-nodeify#examples

**Comment by endel** [comment]
@Goblin-Knight cool, thanks for sharing the solution! I've just included this new instruction in the README file: https://github.com/gamestdio/colyseus.js/#react-native-compatibility
