### ISSUE TITLE
Cocos Creator should use 'cc.sys.localStorage' instead of 'window.localStorage'

### ISSUE THREAD

**Issue by FredDull** [gamestdio/colyseus.js#21]
In my case, I use cocos creator to build mobile games, all javascript program are running in v8 engine just like nodejs. So there's no 'window' object. We use 'cc.sys.localStorge' instead of it. In browsers, 'cc.sys.localStorge' uses window.localStorge and in mobiles it uses sqlite.
'cc.sys.localStorge' is a part of cocos-js.

**Comment by FredDull** [comment]
I think I know how to do it:
put 'window.localStorge = cc.sys.localStorge;' in line 1 and the app runs correctly.
But, is it OK to set a readonly var??

**Comment by FredDull** [comment]
plus 'if (cc.sys.isNative)' now it's good enough.

**Comment by endel** [comment]
Hi @FredDull, thanks for letting me know. 

I've never had experience with Cocos Creator, as this library is supposed to work on every browser-related project, I think it makes sense to have this check in the main library. 

I'll let this issue opened until this check is done in the main library.
Cheers!

**Comment by endel** [comment]
Another compatiblity issue with Cocos Creator: https://github.com/gamestdio/websocket/issues/3

**Comment by endel** [comment]
The latest version has a check for `cc.sys. localStorage` and use it if it's available.
