### ISSUE TITLE
How can I get a colyseus.d.ts for typescript?

### ISSUE THREAD

**Issue by FredDull** [gamestdio/colyseus.js#22]
Is it possible?

**Comment by FredDull** [comment]
with the help of webstorm with node & npm support, I don't need colyseus.d.ts any more.

**Comment by endel** [comment]
Reopening. 

Would be handy to have this file to support environments that need to load files in the old-fashion way, such as Egret (https://github.com/gamestdio/colyseus.js/issues/18) and Cocos Creator (https://github.com/gamestdio/colyseus.js/issues/8).

**Comment by endel** [comment]
Global type definitions are finally available on [`colyseus.d.ts`](https://github.com/gamestdio/colyseus.js/blob/master/dist/colyseus.d.ts).

Thanks a lot @AlexanderKolarov for his pull-request (https://github.com/gamestdio/colyseus.js/pull/27)
