### ISSUE TITLE
Typescript + namespaces(browser) cannot use client colyseus(typescript).

### ISSUE THREAD

**Issue by AlexanderKolarov** [gamestdio/colyseus.js#26]
Im making browser game with namespaces in typescript. I cannot figure it out how to use colyseus client in typescript on namespaces. Maybe it is impossible ?

It would be good to have only one definition file also.

If it is impossible maybe Ill make colyseus client on namespaces(not modules) with single defintion file.

**Comment by endel** [comment]
Hey @alexanderKolarov,

Currently, the only way to use it in a global (namespaced) environment, is by copying the dist [colyseus.js](https://github.com/gamestdio/colyseus.js/blob/master/dist/colyseus.js) file into your project, and defining the module for TypeScript, like:

```
/// colyseus.d.ts
declare var Colyseus: any;
```

Related issues: https://github.com/gamestdio/colyseus.js/issues/22, https://github.com/gamestdio/colyseus.js/issues/18, https://github.com/gamestdio/colyseus.js/issues/8

**Comment by alexanderKolarov** [comment]
Thanks for the replay. 
I like Colyseus - frontend, backend.

And I made definition files with namespace on typescript.
I just created typescript project with tsconfig.module = "none", outFile:"colyseus.js", declaration:true. Than created all classes with empty properties, functions but typed, under Colyseus namespace.

So the new d.ts files work, at least up to room.onJoin() invoking. Need more work on it the be fully supported and good typed.

What should I have to do on github?

**Comment by endel** [comment]
That's great @AlexanderKolarov! Glad you're liking using it so far!

Do you mind sending a pull-request adding the `colyseus.d.ts` into the [`dist/`](https://github.com/gamestdio/colyseus.js/tree/master/dist) folder?

**Comment by AlexanderKolarov** [comment]
@endel , I made pull request. It can be viewed here: #27 .

**Comment by endel** [comment]
@AlexanderKolarov that's excellent! Thank you very much! I'm sure this will be helpful for more users.

I didn't know about the `tsconfig.module = "none"`. Nice one!

Cheers!
