### ISSUE TITLE
0.6.0: allow to receive arbitrary messages from server

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus.js#4]
`onMessage` signal is being triggered only for a specific message kind. It needs to be triggered for any message. 

https://github.com/gamestdio/colyseus.js/blob/master/src/Client.ts#L117

(reported by @AnubisCode on Gitter, thanks!)

**Comment by AnubisCode** [comment]
#5 this

**Comment by endel** [comment]
Thanks @AnubisCode, just published version `0.6.0-alpha.1` with your fix 👏
