### ISSUE TITLE
con it use in the cocos creator?

### ISSUE THREAD

**Issue by ruifly2012** [gamestdio/colyseus.js#8]
con it use in the cocos creator?

**Comment by endel** [comment]
Hi @ruifly2012, I think you're looking for this client instead (C++): https://github.com/chunho32/colyseus-cocos2d-x

**Comment by endel** [comment]
After reading a bit about Cocos Creator, I think you can actually use Colyseus's JavaScript client directly, by downloading the compiled distribution file: https://github.com/gamestdio/colyseus.js/blob/master/dist/colyseus.js

It would work only targeting the web platform, though. For native platform, the C++ client would be necessary.

**Comment by endel** [comment]
Global type definitions are finally available on [`colyseus.d.ts`](https://github.com/gamestdio/colyseus.js/blob/master/dist/colyseus.d.ts).

Thanks a lot @AlexanderKolarov for his pull-request (https://github.com/gamestdio/colyseus.js/pull/27)

**Comment by yinjimmy** [comment]
An example with cocos creator https://gitee.com/limo/simple_server , build with colyseus 0.9.33.
