### ISSUE TITLE
typescript module missing in definition files

### ISSUE THREAD

**Issue by markokristian** [gamestdio/colyseus.js#9]
Maybe I am blind, but I could not find a module declaration called "colyseus.js" anywhere in the package.

Wanted to use this library in my TS-project.

My workaround was to use a [shorthand declaration](https://www.typescriptlang.org/docs/handbook/modules.html). E.g.

`declare module "colyseus.js";`

But this will only import "any", even if it makes the project compile and works runtime.

I might have misunderstood how to import this library to my project, so please enlighten me in that case.

**Comment by endel** [comment]
Hi @markokristian, can you provide more details about your environment and how are you building your project? I'd like to cover all possible scenarios.

AFAIK, if you're using `"module": "commonjs"` in your `tsconfig.json`, you should be able to import this module and use its type definitions out of the box:

```typescript
import { Client, Room } from "colyseus.js";
```

**Comment by endel** [comment]
Not going to support static type definitions, workaround here: https://github.com/gamestdio/colyseus.js/issues/18#issuecomment-353970650

Feel free to reopen this issue if you'd like to. Cheers!
